### ISSUE TITLE
Simple

### ISSUE THREAD

**Issue by martab0** [guinea-pigg/Vistula-text#7]
Subiektywnie nie lubię określeń "simple", "easy" itd. w dokumentacji. Materiał poglądowy: https://youtu.be/gsT2BBWBVmM?si=oflyzBeQDkrQo0Ga
Dlatego "6 powerful tips" byłoby chyba lepsze :-) Ale sam pomysł i sposób skrócenia tytułu jest bdb!

**Comment by guinea-pigg** [comment]
Rzeczywiście, "simple", "easy" brzmią mocno subiektywnie, a wiadomo, że tą samą rzecz dwie różne osoby mogą oceniać kompletnie inaczej. Dziękuję!
